[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
optimizer = true
optimizer_runs = 18_000
evm_version="Istanbul"

remappings = [
    '@uniswap/v2-core/=lib/v2-core/contracts/',
    '@uniswap/v2-core/=lib/v2-core/contracts/',
]